export type AdminApiErrorCode =
  | "UNAUTHENTICATED"
  | "TOKEN_EXPIRED"
  | "INVALID_TOKEN"
  | "MFA_REQUIRED"
  | "MFA_INVALID"
  | "MFA_ALREADY_ENABLED"
  | "MFA_NOT_ENROLLED"
  | "INVALID_CREDENTIALS"
  | "INVALID_REFRESH_TOKEN"
  | "ADMIN_DISABLED"
  | "FORBIDDEN"
  | "EMAIL_TAKEN"
  | "NOT_FOUND"
  | "SYSTEM_ROLE_IMMUTABLE"
  | "INSUFFICIENT_BALANCE"
  | "SELF_ROLE_EDIT"
  | "DUPLICATE_ADJUSTMENT"
  | "WITHDRAWAL_NOT_PENDING"
  | "WITHDRAWAL_NOT_RECONCILABLE"
  | "GATEWAY_ERROR"
  | "KYC_NOT_PENDING"
  | "REASON_REQUIRED"
  | "REFERRAL_NOT_ELIGIBLE"
  | "REFERRAL_ALREADY_REWARDED"
  | "REFERRAL_NOT_REWARDED"
  | "CAMPAIGN_NOT_FOUND"

export class AdminApiError extends Error {
  constructor(
    public readonly code: AdminApiErrorCode,
    message: string
  ) {
    super(message)
    this.name = "AdminApiError"
  }
}

const STATUS_BY_CODE: Record<AdminApiErrorCode, number> = {
  UNAUTHENTICATED: 401,
  TOKEN_EXPIRED: 401,
  INVALID_TOKEN: 401,
  MFA_REQUIRED: 401,
  MFA_INVALID: 401,
  MFA_ALREADY_ENABLED: 409,
  MFA_NOT_ENROLLED: 422,
  INVALID_CREDENTIALS: 401,
  INVALID_REFRESH_TOKEN: 401,
  ADMIN_DISABLED: 403,
  FORBIDDEN: 403,
  EMAIL_TAKEN: 409,
  NOT_FOUND: 404,
  SYSTEM_ROLE_IMMUTABLE: 409,
  INSUFFICIENT_BALANCE: 422,
  SELF_ROLE_EDIT: 403,
  DUPLICATE_ADJUSTMENT: 409,
  WITHDRAWAL_NOT_PENDING: 409,
  WITHDRAWAL_NOT_RECONCILABLE: 409,
  GATEWAY_ERROR: 502,
  KYC_NOT_PENDING: 409,
  REASON_REQUIRED: 422,
  REFERRAL_NOT_ELIGIBLE: 409,
  REFERRAL_ALREADY_REWARDED: 409,
  REFERRAL_NOT_REWARDED: 409,
  CAMPAIGN_NOT_FOUND: 404,
}

export function statusForError(err: AdminApiError): number {
  return STATUS_BY_CODE[err.code]
}
