/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardCasinoRouteImport } from './routes/dashboard.casino'
import { Route as DashboardExchangeRouteImport } from './routes/dashboard.exchange'
import { Route as DashboardLiveCasinoRouteImport } from './routes/dashboard.live-casino'
import { Route as DashboardPromotionsRouteImport } from './routes/dashboard.promotions'
import { Route as DashboardProvidersRouteImport } from './routes/dashboard.providers'
import { Route as DashboardSportsbookRouteImport } from './routes/dashboard.sportsbook'
import { Route as GameGameSlugRouteImport } from './routes/game.$gameSlug'
import { Route as DashboardAccountIndexRouteImport } from './routes/dashboard.account.index'
import { Route as DashboardAccountAddBankRouteImport } from './routes/dashboard.account.add-bank'
import { Route as DashboardAccountDepositRouteImport } from './routes/dashboard.account.deposit'
import { Route as DashboardAccountHistoryRouteImport } from './routes/dashboard.account.history'
import { Route as DashboardAccountLoyaltyRouteImport } from './routes/dashboard.account.loyalty'
import { Route as DashboardAccountProfileRouteImport } from './routes/dashboard.account.profile'
import { Route as DashboardAccountWithdrawRouteImport } from './routes/dashboard.account.withdraw'
import { Route as DashboardCategoryCategoryCodeRouteImport } from './routes/dashboard.category.$categoryCode'
import { Route as DashboardGamesSlugRouteImport } from './routes/dashboard.games.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasinoRoute = DashboardCasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExchangeRoute = DashboardExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveCasinoRoute = DashboardLiveCasinoRouteImport.update({
  id: '/live-casino',
  path: '/live-casino',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromotionsRoute = DashboardPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvidersRoute = DashboardProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSportsbookRoute = DashboardSportsbookRouteImport.update({
  id: '/sportsbook',
  path: '/sportsbook',
  getParentRoute: () => DashboardRoute,
} as any)
const GameGameSlugRoute = GameGameSlugRouteImport.update({
  id: '/game/$gameSlug',
  path: '/game/$gameSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAccountRoute,
} as any)
const DashboardAccountAddBankRoute = DashboardAccountAddBankRouteImport.update({
  id: '/add-bank',
  path: '/add-bank',
  getParentRoute: () => DashboardAccountRoute,
} as any)
const DashboardAccountDepositRoute = DashboardAccountDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => DashboardAccountRoute,
} as any)
const DashboardAccountHistoryRoute = DashboardAccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardAccountRoute,
} as any)
const DashboardAccountLoyaltyRoute = DashboardAccountLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => DashboardAccountRoute,
} as any)
const DashboardAccountProfileRoute = DashboardAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardAccountRoute,
} as any)
const DashboardAccountWithdrawRoute =
  DashboardAccountWithdrawRouteImport.update({
    id: '/withdraw',
    path: '/withdraw',
    getParentRoute: () => DashboardAccountRoute,
  } as any)
const DashboardCategoryCategoryCodeRoute =
  DashboardCategoryCategoryCodeRouteImport.update({
    id: '/category/$categoryCode',
    path: '/category/$categoryCode',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGamesSlugRoute = DashboardGamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/dashboard/account': typeof DashboardAccountRouteWithChildren
  '/dashboard/casino': typeof DashboardCasinoRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/live-casino': typeof DashboardLiveCasinoRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/sportsbook': typeof DashboardSportsbookRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/add-bank': typeof DashboardAccountAddBankRoute
  '/dashboard/account/deposit': typeof DashboardAccountDepositRoute
  '/dashboard/account/history': typeof DashboardAccountHistoryRoute
  '/dashboard/account/loyalty': typeof DashboardAccountLoyaltyRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/withdraw': typeof DashboardAccountWithdrawRoute
  '/dashboard/category/$categoryCode': typeof DashboardCategoryCategoryCodeRoute
  '/dashboard/games/$slug': typeof DashboardGamesSlugRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/dashboard/casino': typeof DashboardCasinoRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/live-casino': typeof DashboardLiveCasinoRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/sportsbook': typeof DashboardSportsbookRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/account/add-bank': typeof DashboardAccountAddBankRoute
  '/dashboard/account/deposit': typeof DashboardAccountDepositRoute
  '/dashboard/account/history': typeof DashboardAccountHistoryRoute
  '/dashboard/account/loyalty': typeof DashboardAccountLoyaltyRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/withdraw': typeof DashboardAccountWithdrawRoute
  '/dashboard/category/$categoryCode': typeof DashboardCategoryCategoryCodeRoute
  '/dashboard/games/$slug': typeof DashboardGamesSlugRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/dashboard/account': typeof DashboardAccountRouteWithChildren
  '/dashboard/casino': typeof DashboardCasinoRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/live-casino': typeof DashboardLiveCasinoRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/sportsbook': typeof DashboardSportsbookRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/add-bank': typeof DashboardAccountAddBankRoute
  '/dashboard/account/deposit': typeof DashboardAccountDepositRoute
  '/dashboard/account/history': typeof DashboardAccountHistoryRoute
  '/dashboard/account/loyalty': typeof DashboardAccountLoyaltyRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/withdraw': typeof DashboardAccountWithdrawRoute
  '/dashboard/category/$categoryCode': typeof DashboardCategoryCategoryCodeRoute
  '/dashboard/games/$slug': typeof DashboardGamesSlugRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/help-center'
    | '/login'
    | '/responsible-gaming'
    | '/dashboard/account'
    | '/dashboard/casino'
    | '/dashboard/exchange'
    | '/dashboard/live-casino'
    | '/dashboard/promotions'
    | '/dashboard/providers'
    | '/dashboard/sportsbook'
    | '/game/$gameSlug'
    | '/dashboard/'
    | '/dashboard/account/add-bank'
    | '/dashboard/account/deposit'
    | '/dashboard/account/history'
    | '/dashboard/account/loyalty'
    | '/dashboard/account/profile'
    | '/dashboard/account/withdraw'
    | '/dashboard/category/$categoryCode'
    | '/dashboard/games/$slug'
    | '/dashboard/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/help-center'
    | '/login'
    | '/responsible-gaming'
    | '/dashboard/casino'
    | '/dashboard/exchange'
    | '/dashboard/live-casino'
    | '/dashboard/promotions'
    | '/dashboard/providers'
    | '/dashboard/sportsbook'
    | '/game/$gameSlug'
    | '/dashboard'
    | '/dashboard/account/add-bank'
    | '/dashboard/account/deposit'
    | '/dashboard/account/history'
    | '/dashboard/account/loyalty'
    | '/dashboard/account/profile'
    | '/dashboard/account/withdraw'
    | '/dashboard/category/$categoryCode'
    | '/dashboard/games/$slug'
    | '/dashboard/account'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/help-center'
    | '/login'
    | '/responsible-gaming'
    | '/dashboard/account'
    | '/dashboard/casino'
    | '/dashboard/exchange'
    | '/dashboard/live-casino'
    | '/dashboard/promotions'
    | '/dashboard/providers'
    | '/dashboard/sportsbook'
    | '/game/$gameSlug'
    | '/dashboard/'
    | '/dashboard/account/add-bank'
    | '/dashboard/account/deposit'
    | '/dashboard/account/history'
    | '/dashboard/account/loyalty'
    | '/dashboard/account/profile'
    | '/dashboard/account/withdraw'
    | '/dashboard/category/$categoryCode'
    | '/dashboard/games/$slug'
    | '/dashboard/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  HelpCenterRoute: typeof HelpCenterRoute
  LoginRoute: typeof LoginRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  GameGameSlugRoute: typeof GameGameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/casino': {
      id: '/dashboard/casino'
      path: '/casino'
      fullPath: '/dashboard/casino'
      preLoaderRoute: typeof DashboardCasinoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exchange': {
      id: '/dashboard/exchange'
      path: '/exchange'
      fullPath: '/dashboard/exchange'
      preLoaderRoute: typeof DashboardExchangeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live-casino': {
      id: '/dashboard/live-casino'
      path: '/live-casino'
      fullPath: '/dashboard/live-casino'
      preLoaderRoute: typeof DashboardLiveCasinoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/promotions': {
      id: '/dashboard/promotions'
      path: '/promotions'
      fullPath: '/dashboard/promotions'
      preLoaderRoute: typeof DashboardPromotionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/providers': {
      id: '/dashboard/providers'
      path: '/providers'
      fullPath: '/dashboard/providers'
      preLoaderRoute: typeof DashboardProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sportsbook': {
      id: '/dashboard/sportsbook'
      path: '/sportsbook'
      fullPath: '/dashboard/sportsbook'
      preLoaderRoute: typeof DashboardSportsbookRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/game/$gameSlug': {
      id: '/game/$gameSlug'
      path: '/game/$gameSlug'
      fullPath: '/game/$gameSlug'
      preLoaderRoute: typeof GameGameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/account/': {
      id: '/dashboard/account/'
      path: '/'
      fullPath: '/dashboard/account/'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardAccountRoute
    }
    '/dashboard/account/add-bank': {
      id: '/dashboard/account/add-bank'
      path: '/add-bank'
      fullPath: '/dashboard/account/add-bank'
      preLoaderRoute: typeof DashboardAccountAddBankRouteImport
      parentRoute: typeof DashboardAccountRoute
    }
    '/dashboard/account/deposit': {
      id: '/dashboard/account/deposit'
      path: '/deposit'
      fullPath: '/dashboard/account/deposit'
      preLoaderRoute: typeof DashboardAccountDepositRouteImport
      parentRoute: typeof DashboardAccountRoute
    }
    '/dashboard/account/history': {
      id: '/dashboard/account/history'
      path: '/history'
      fullPath: '/dashboard/account/history'
      preLoaderRoute: typeof DashboardAccountHistoryRouteImport
      parentRoute: typeof DashboardAccountRoute
    }
    '/dashboard/account/loyalty': {
      id: '/dashboard/account/loyalty'
      path: '/loyalty'
      fullPath: '/dashboard/account/loyalty'
      preLoaderRoute: typeof DashboardAccountLoyaltyRouteImport
      parentRoute: typeof DashboardAccountRoute
    }
    '/dashboard/account/profile': {
      id: '/dashboard/account/profile'
      path: '/profile'
      fullPath: '/dashboard/account/profile'
      preLoaderRoute: typeof DashboardAccountProfileRouteImport
      parentRoute: typeof DashboardAccountRoute
    }
    '/dashboard/account/withdraw': {
      id: '/dashboard/account/withdraw'
      path: '/withdraw'
      fullPath: '/dashboard/account/withdraw'
      preLoaderRoute: typeof DashboardAccountWithdrawRouteImport
      parentRoute: typeof DashboardAccountRoute
    }
    '/dashboard/category/$categoryCode': {
      id: '/dashboard/category/$categoryCode'
      path: '/category/$categoryCode'
      fullPath: '/dashboard/category/$categoryCode'
      preLoaderRoute: typeof DashboardCategoryCategoryCodeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/games/$slug': {
      id: '/dashboard/games/$slug'
      path: '/games/$slug'
      fullPath: '/dashboard/games/$slug'
      preLoaderRoute: typeof DashboardGamesSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardAccountRouteChildren {
  DashboardAccountAddBankRoute: typeof DashboardAccountAddBankRoute
  DashboardAccountDepositRoute: typeof DashboardAccountDepositRoute
  DashboardAccountHistoryRoute: typeof DashboardAccountHistoryRoute
  DashboardAccountLoyaltyRoute: typeof DashboardAccountLoyaltyRoute
  DashboardAccountProfileRoute: typeof DashboardAccountProfileRoute
  DashboardAccountWithdrawRoute: typeof DashboardAccountWithdrawRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
}

const DashboardAccountRouteChildren: DashboardAccountRouteChildren = {
  DashboardAccountAddBankRoute: DashboardAccountAddBankRoute,
  DashboardAccountDepositRoute: DashboardAccountDepositRoute,
  DashboardAccountHistoryRoute: DashboardAccountHistoryRoute,
  DashboardAccountLoyaltyRoute: DashboardAccountLoyaltyRoute,
  DashboardAccountProfileRoute: DashboardAccountProfileRoute,
  DashboardAccountWithdrawRoute: DashboardAccountWithdrawRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
}

const DashboardAccountRouteWithChildren =
  DashboardAccountRoute._addFileChildren(DashboardAccountRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRouteWithChildren
  DashboardCasinoRoute: typeof DashboardCasinoRoute
  DashboardExchangeRoute: typeof DashboardExchangeRoute
  DashboardLiveCasinoRoute: typeof DashboardLiveCasinoRoute
  DashboardPromotionsRoute: typeof DashboardPromotionsRoute
  DashboardProvidersRoute: typeof DashboardProvidersRoute
  DashboardSportsbookRoute: typeof DashboardSportsbookRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCategoryCategoryCodeRoute: typeof DashboardCategoryCategoryCodeRoute
  DashboardGamesSlugRoute: typeof DashboardGamesSlugRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRouteWithChildren,
  DashboardCasinoRoute: DashboardCasinoRoute,
  DashboardExchangeRoute: DashboardExchangeRoute,
  DashboardLiveCasinoRoute: DashboardLiveCasinoRoute,
  DashboardPromotionsRoute: DashboardPromotionsRoute,
  DashboardProvidersRoute: DashboardProvidersRoute,
  DashboardSportsbookRoute: DashboardSportsbookRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCategoryCategoryCodeRoute: DashboardCategoryCategoryCodeRoute,
  DashboardGamesSlugRoute: DashboardGamesSlugRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  HelpCenterRoute: HelpCenterRoute,
  LoginRoute: LoginRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  GameGameSlugRoute: GameGameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
